##
## EPITECH PROJECT, 2019
## Ceasar
## File description:
## Ceasar
##

RM	=
SRC1	=	ex1.py

SRC2	=	ex2.py

SRC3	=	ex3.py

SRC4	=	ex4.py

SRC5	=	ex5.py

SRC6	=	ex6.py

SRC7 	=	ex7.py

SRC8 	=	ex8.py

SRC9 	=	ex9.py

SRC10 	=	ex10.py

SRC11 	=	ex11.py

SRC12 	=	ex12.py

SRC13 	=	ex13.py

SRC14	=	ex14.py

all:
	cp $(SRC1) challenge01
	chmod +x challenge01
	cp $(SRC2) challenge02
	chmod +x challenge02
	cp $(SRC3) challenge03
	chmod +x challenge03
	cp $(SRC4) challenge04
	chmod +x challenge04
	cp $(SRC5) challenge05
	chmod +x challenge05
	cp $(SRC6) challenge06
	chmod +x challenge06
	cp $(SRC7) challenge07
	chmod +x challenge07
	cp $(SRC8) challenge08
	chmod +x challenge08
	cp $(SRC9) challenge09
	chmod +x challenge09
	cp $(SRC10) challenge10
	chmod +x challenge10
	cp $(SRC11) challenge11
	chmod +x challenge11
	cp $(SRC12) challenge12
	chmod +x challenge12
	cp $(SRC13) challenge13
	chmod +x challenge13
	cp $(SRC14) challenge14
	chmod +x challenge14

%: %.py
	chmod +x $<
	cp $< $@

clean:
	rm -f challenge*
	rm -f *~
re: clean all

.PHONY: all clean re
